### ISSUE TITLE
Crash when running on Android 4.2

### ISSUE THREAD

**Issue by weimingtom** [fython/NHentai-android#1]
Crash when running on Android 4.2, because getExternalCacheDir() returns null.

1. Device: 
	红米1 (Xiaomi 2013022, Android 4.2.1 API 17)

2. Code:
	commit fc7822c5258e36342e4e4a1d8e5dbd3867d8148d
	Date:   Sat Jul 4 16:34:14 2015 +0800
		Fix some problems caused by FavoriteManager
	
3. Exception StackTrace:
07-14 09:42:26.468    8328-8328/moe.feng.nhentai E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.feng.nhentai/moe.feng.nhentai.ui.BookDetailsActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2333)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2385)
            at android.app.ActivityThread.access$600(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5326)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at moe.feng.nhentai.cache.file.FileCacheManager.getCachePath(FileCacheManager.java:204)
            at moe.feng.nhentai.cache.file.FileCacheManager.cacheExists(FileCacheManager.java:144)
            at moe.feng.nhentai.cache.file.FileCacheManager.cacheExistsUrl(FileCacheManager.java:140)
            at moe.feng.nhentai.ui.BookDetailsActivity.onCreate(BookDetailsActivity.java:89)
            at android.app.Activity.performCreate(Activity.java:5222)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2385)
            at android.app.ActivityThread.access$600(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5326)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
            at dalvik.system.NativeStart.main(Native Method)

4. My patches 
(1) FileCacheManager.java
	private FileCacheManager(Context context) {
		mCacheDir = context.getExternalCacheDir();
		if (mCacheDir == null) {
			final String cacheDir = "/Android/data/" + context.getPackageName() + "/cache/";
			mCacheDir =  new File(Environment.getExternalStorageDirectory().getPath() + cacheDir);
			//mCacheDir.mkdirs();
		}
	}
(2) AndroidManifest.xml
    uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
    uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"

**Comment by fython** [comment]
Thanks for your suggestion.

Fixed via 06017bd231edd33054134b0b8664ad23ea36c13d
